[[redirects]]
  from = "/api/core/*"
  to = "https://dev.api.bekindnetwork.com/api/v1/:splat"
  status = 200
  force = false
  headers = {X-From = "Netlify"}

  [[headers]]
  for = "/api/core/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200